In [1]:
#!/usr/bin/env python
import wuml 
import numpy as np

M = wuml.gen_squared_symmetric_matrix(4, distribution='Uniform')
data = wuml.wData(X_npArray=M)
print(data)

2021-10-12 13:33:51.544816: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


          0         1         2         3
0  1.472913  1.444118  1.568513  1.064021
1  1.444118  1.583404  1.474026  0.947276
2  1.568513  1.474026  1.982232  1.004639
3  1.064021  0.947276  1.004639  1.192041


In [2]:
E = wuml.eig(data, num_eigs_to_keep=2, return_contribution_of_each_vector=True)
[Λ, V, Λₐ, Vₐ]= [E.eigen_values, E.eigen_vectors, E.all_eigen_values, E.all_eigen_vectors]
M_back = Vₐ.dot(Λₐ).dot(Vₐ.T)
print('Eigenvalues and Eigenvectors')
wuml.block_two_string_concatenate(Λₐ, Vₐ, spacing='\t', add_titles=['Eigenvalues', 'Eigenvectors'], auto_print=True)

Eigenvalues and Eigenvectors
          Eigenvalues          	            Eigenvectors           
[[5.403  0.     0.     0.    ] 	[[-0.5184  0.0133  0.1067 -0.8483]
 [0.     0.514  0.     0.    ] 	 [-0.5106 -0.1341  0.7471  0.4039]
 [0.     0.     0.2894 0.    ] 	 [-0.5699 -0.4746 -0.617   0.2632]
 [0.     0.     0.     0.0242]]	 [-0.3818  0.8698 -0.2231  0.2189]]



In [3]:
print('Making sure the eigenvectors and values can returns the same matrix.\n\t(M and M_back should be identical)')
wuml.block_two_string_concatenate(M, M_back, spacing='\t', add_titles=['M', 'M from Eigs'], auto_print=True)

Making sure the eigenvectors and values can returns the same matrix.
	(M and M_back should be identical)
               M               	          M from Eigs          
[[1.4729 1.4441 1.5685 1.064 ] 	[[1.4729 1.4441 1.5685 1.064 ]
 [1.4441 1.5834 1.474  0.9473] 	 [1.4441 1.5834 1.474  0.9473]
 [1.5685 1.474  1.9822 1.0046] 	 [1.5685 1.474  1.9822 1.0046]
 [1.064  0.9473 1.0046 1.192 ]]	 [1.064  0.9473 1.0046 1.192 ]]



In [4]:
wuml.pretty_np_array(E.data_projected_onto_eigvectors, title='Project X onto V : VᵀX', auto_print=True)

      Project X onto V : VᵀX     
[-2.8011 -2.7588 -3.079  -2.0629]
[ 0.0068 -0.0689 -0.2439  0.447 ]
[ 0.0309  0.2162 -0.1786 -0.0646]
[-0.0205  0.0098  0.0064  0.0053]



In [5]:
print('Study how quickly the eigenvalues grow')
wuml.pretty_np_array(E.cumsum_eigen_values, title='cumsum eigenvalues', auto_print=True)

Study how quickly the eigenvalues grow
      cumsum eigenvalues     
[0.8672 0.9497 0.9961 1.    ]



In [6]:
print('Study the weights of the eigenvalues')
wuml.pretty_np_array(E.normalized_eigen_values, title='Normalized eigenvalues', auto_print=True)

Study the weights of the eigenvalues
    Normalized eigenvalues   
[0.8672 0.0825 0.0465 0.0039]

