In [1]:
#!/usr/bin/env python

In [2]:
import os
import sys
if os.path.exists('/home/chieh/code/wPlotLib'):
	sys.path.insert(0,'/home/chieh/code/wPlotLib')
if os.path.exists('/home/chieh/code/wuML'):
	sys.path.insert(0,'/home/chieh/code/wuML')

In [3]:
import wuml
import numpy as np
import torch
import torch
import torch.nn as nn

In [4]:
def costFunction(x, x̂, ẙ, y, ŷ, ind):	
#	x -> encoder -> x̂
#	x̂ -> encoder_linear_output -> ẙ	
#	x̂ -> decoder -> ŷ	
#	possible autoencoder objective λ could be 0
#	loss = (x - ŷ)ᒾ + λ * objective(ẙ, y)
#
#	This function can return 1 value or 3 values in a list
#	if return 1 value, just the loss
#	if return 3 values, [total_loss, reconstruction_loss, extra network from ẙ loss]
#
#	In this example, we perform both reconstruction and CE loss
#
	CE_loss = nn.CrossEntropyLoss() #weird pytorch, dim of y is 1, and ŷ is 20x3
	R = torch.sum((x - ŷ) ** 2)/(128*13)	#scaled by batch size times data dimension
	CE = CE_loss(ẙ, y)
	loss = R + CE
	return [loss, R, CE]

In [5]:
def costFunction2(x, x̂, ẙ, y, ŷ, ind):	
#	Example of just return 1 value, this is just a regular autoencoder
	return torch.sum((x - ŷ) ** 2)

In [6]:
data = wuml.wData(xpath='../../data/wine.csv', ypath='../../data/wine_label.csv', 
					preprocess_data='center and scale', batch_size=128, label_type='discrete')

In [7]:
AE = wuml.autoencoder(12, data, default_depth=2, costFunction=costFunction, # costFunction and costFunction2 both works
						max_epoch=2000, encoder_output_weight_structure=[(3,'none')] ) 
AE.fit()
wuml.save_torch_network(AE, './autoencoder.pk')

	epoch: 2000, Total Loss/dimension: 0.0148, Reconstruct loss: 0.0145, Objective loss: 0.0002, Learning Rate: 0.00012500

Notice that the reconstruction did a reasonable job

In [8]:
ŷ = AE(data)
wuml.jupyter_print(ŷ[0:5,0:10])
wuml.jupyter_print(data.X[0:5,0:10])

[[ 1.5223 -0.5796  0.3025 -1.2149  1.9172  0.8452  1.1236 -0.6894  1.2094  0.1791]
 [ 0.2461 -0.5118 -0.8183 -2.475  -0.0005  0.6424  0.5768 -0.841  -0.4962 -0.3521]
 [ 0.2226 -0.0273  1.0132 -0.2279  0.1785  1.0491  1.2664 -0.3817  1.9472  0.358 ]
 [ 1.5981 -0.2328  0.5082 -0.8593  0.8719  1.8772  1.8637 -1.038   1.1726  1.2296]
 [ 0.2316  0.2322  1.7682  0.5063  1.2899  0.7305  0.7314  0.2665  0.3914 -0.3258]]


0         1         2         3         4         5         6  \
0  1.518613 -0.562250  0.232053 -1.169593  1.913905  0.808997  1.034819   
1  0.246290 -0.499413 -0.827996 -2.490847  0.018145  0.568648  0.733629   
2  0.196879  0.021231  1.109334 -0.268738  0.088358  0.808997  1.215533   
3  1.691550 -0.346811  0.487926 -0.809251  0.930918  2.491446  1.466525   
4  0.295700  0.227694  1.840403  0.451946  1.281985  0.808997  0.663351   

          7         8         9  
0 -0.659563  1.224884  0.251717  
1 -0.820719 -0.544721 -0.293321  
2 -0.498407  2.135968  0.269020  
3 -0.981875  1.032155  1.186068  
4  0.226796  0.401404 -0.319276

This is the bottleneck output which is d=12

In [9]:
x̂ = AE.reduce_dimension(data, output_type='wData')
wuml.jupyter_print(x̂.shape)

This is the objective network output 

In [10]:
ẙ = AE.objective_network(data)

Here we use the bottleneck to perform SVM classification

In [11]:
cf = wuml.classification(x̂, classifier='SVM')
wuml.jupyter_print(cf.result_summary(print_out=False))

Here we use the objective network output to perform LogisticRegression classification

In [12]:
cf = wuml.classification(ẙ, classifier='LogisticRegression')
wuml.jupyter_print(cf.result_summary(print_out=False))