In [1]:
#!/usr/bin/env python

In [2]:
import os
import sys
if os.path.exists('/home/chieh/code/wPlotLib'):
	sys.path.insert(0,'/home/chieh/code/wPlotLib')
if os.path.exists('/home/chieh/code/wuML'):
	sys.path.insert(0,'/home/chieh/code/wuML')
import wuml
import wplotlib
import numpy as np
import sklearn
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

On lower dimension data, it seems that RFF is good enough

In [3]:
X = np.random.randn(7,4)
σ = np.median(sklearn.metrics.pairwise.pairwise_distances(X))
γ = 1.0/(2*σ*σ)
#
K = sklearn.metrics.pairwise.rbf_kernel(X, gamma=γ)
#
sorf = wuml.random_feature(sigma=σ, random_feature_method='orthogonal', sample_num=12)
Kₒ = sorf.get_kernel(X)			# kernel matrix from orthogonal

In [4]:
wuml.jupyter_print('You can obtain the feature map directly via the function get_feature_map')
Φₒ = sorf.get_feature_map(X)			# kernel matrix from orthogonal
wuml.jupyter_print(Φₒ); print('\n')

[[-0.2139  0.1712 -0.0848 -0.4066 -0.2117 -0.0358  0.3929  0.4055 -0.2028  0.35    0.1298 -0.4082]
 [-0.3499  0.0083  0.4014  0.0939 -0.3435 -0.3975  0.2977  0.3906  0.3756  0.192  -0.0261 -0.3606]
 [ 0.1147 -0.3644  0.2254 -0.4081 -0.3973  0.0101  0.3457  0.0618 -0.3996  0.2253 -0.1884 -0.4054]
 [-0.2276 -0.3338  0.3334 -0.2713 -0.4043 -0.3044  0.3881  0.1198 -0.0952  0.1874 -0.2295 -0.3595]
 [-0.3853 -0.3583  0.3863  0.1274 -0.3719 -0.3882  0.235   0.0748  0.2611  0.0312 -0.2291 -0.1284]
 [-0.011  -0.0845  0.1237 -0.3466  0.1763  0.2165  0.3956 -0.4059 -0.3895 -0.3504 -0.0809 -0.3694]
 [-0.2358 -0.0026  0.3519  0.3501 -0.3982 -0.2108  0.3849  0.3872  0.3763  0.018   0.264  -0.264 ]]




In [5]:
rff = wuml.random_feature(sigma=σ, random_feature_method='rff')
Kᵣ = rff.get_kernel(X)			# kernel matrix from orthogonal
#
#
wuml.print_two_matrices_side_by_side(K[0:8,0:8], Kₒ[0:8,0:8], title1='Real', title2='Approx by SORF', auto_print=True)
wuml.print_two_matrices_side_by_side(K[0:8,0:8], Kᵣ[0:8,0:8], title1='Real', title2='Approx by RFF', auto_print=True)

                       Real                       	Approx by SORF                  
[1.     0.4794 0.6296 0.6173 0.365  0.0699 0.365 ]	[1.     0.8009 0.838  0.9234 0.6067 0.023  0.5568]
[0.4794 1.     0.4186 0.7545 0.8542 0.1138 0.8901]	[0.8009 0.9969 0.377  0.7002 0.8094 0.083  0.8144]
[0.6296 0.4186 1.     0.8109 0.45   0.3333 0.3204]	[0.838  0.377  1.     0.85   0.3197 0.0895 0.1883]
[0.6173 0.7545 0.8109 1.     0.819  0.297  0.6065]	[0.9234 0.7002 0.85   0.9436 0.698  0.2646 0.5099]
[0.365  0.8542 0.45   0.819  1.     0.1865 0.7726]	[0.6067 0.8094 0.3197 0.698  0.9257 0.3101 0.7083]
[0.0699 0.1138 0.3333 0.297  0.1865 1.     0.0631]	[0.023  0.083  0.0895 0.2646 0.3101 0.8969 0.0482]
[0.365  0.8901 0.3204 0.6065 0.7726 0.0631 1.    ]	[0.5568 0.8144 0.1883 0.5099 0.7083 0.0482 0.8393]
                                                  	


                       Real                       	Approx by RFF                   
[1.     0.4794 0.6296 0.6173 0.365  0.0699 0.365 ]	[0.9732 0.540

In [6]:
wuml.jupyter_print("Don't worry that RFF performs better on lower dimension datasets with few samples (only 12)")
ε = mean_absolute_error(K, Kₒ)
wuml.jupyter_print('Mean absolute Error with SORF %.3f'%ε)
ε = mean_absolute_error(K, Kᵣ)
wuml.jupyter_print('Mean absolute Error with RFF %.3f\n'%ε)

In [7]:
ε = mean_squared_error(K, Kₒ)
wuml.jupyter_print('Mean Squared Error with SORF %.3f'%ε)
ε = mean_squared_error(K, Kᵣ)
wuml.jupyter_print('Mean Squared Error with SORF %.3f'%ε)